export const ROUTES = {
  HOME: '/',
  CONTACT: '/contact',
  LIST: '/list',
  POST: (postId: string) => `/post/${postId}`,
  PRODUCT: (slug: string) => `/product/${slug}`,
  CART: '/cart',
  CHECKOUT: '/checkout',
  CHECKOUT_SUCCESS: '/checkout/success',
  CHECKOUT_ERROR: '/checkout/error',
  TRACKING: '/tracking',
  TRACKING_ORDER: (orderNumber: string) => `/tracking/${orderNumber}`,
  PROFILE: (userId: string) => `/profile/${userId}`,
  PROFILE_EDIT: '/profile/edit',
  POST_CREATE: '/post/create',
} as const
